# To restore database backup: Get-Content db\movie.bak | docker exec -i movie-ts_db_1 psql movie -U movie
version: '3'
services:
  app:
    image: node:16.10
    command: sh -c "npm install --include=dev && npm run build && node ./dist/server.js"
    env_file: variables.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    working_dir: /movie
    volumes:
      - .:/movie
    container_name: movie_app
    restart: unless-stopped
  db:
    image: postgres:9.6.22
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: variables.env
    container_name: movie_db
volumes:
  postgres:
